Repository Toonchu-team/toonchu_be, pull requests merged in 2025-02, with the labels that each got.

#11 Feature/user 001
  .gitignore
  config/settings/base.py
  config/urls.py
  poetry.lock
  pyproject.toml
  users/models.py
  users/oauth_mixins.py
  users/urls.py
  users/views.py
Labels: documentation, good first issue, add tech

#13 소셜로그인 URL요청 코드 수정
  config/settings/base.py
  poetry.lock
  users/oauth_mixins.py
  users/views.py
Labels: fix

#14 Feature/user 001
  users/views.py
Labels: fix

#15 logout처리 기능 추가
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement, good first issue, add tech

#17 Feature/user 004 update
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: good first issue, add tech

#22 Fix/user 001
  config/settings/base.py
  config/settings/local.py
  users/migrations/0001_initial.py
  users/models.py
  users/oauth_mixins.py
  users/serializers.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: add tech, fix

#36 Fix/user 001
  users/views.py
Labels: fix

#37 Feature/user 004 delete
  users/delete_users.py
  users/migrations/0001_initial.py
  users/migrations/0002_customuser_is_updated_alter_provider_provider.py
  users/models.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: add tech

#44 Fix/user 002
  users/migrations/0003_alter_customuser_nick_name_alter_customuser_provider.py
  users/models.py
Labels: fix

#46 Fix/user 002
  users/views.py
Labels: add tech, fix

#48 Fix/user 002
  users/views.py
Labels: fix

#49 .....
  users/views.py
Labels: fix

#50 .....
  config/settings/prod.py
  users/views.py
Labels: fix

#51 Fix/user 002
  users/views.py
Labels: fix

#52 수정
  users/views.py
Labels: fix

#54 소셜 settings연결
  users/views.py
Labels: fix

#55 소셜 settings연결
  users/views.py
Labels: fix

#56 token관리
  users/views.py
Labels: fix

#58 Token 관련 로직 추가
  users/serializers.py
  users/urls.py
  users/views.py
Labels: add tech, fix

#63 logoutview import 수정
  users/urls.py
  users/views.py
Labels: fix

#64 user delete부분 parameters추가
  users/views.py
Labels: fix

#65 fix
  users/views.py
Labels: fix

#66 user delete import 수정
  users/views.py
Labels: fix

#68 Fix/user logout
  users/views.py
Labels: fix

#70 Fix/user logout
  users/views.py
Labels: fix

#73 refresh token 인증헤더로
  users/tests.py
  users/views.py
Labels: fix

#75 .
  users/views.py
Labels: fix

#76 authentication_classes 제거
  users/views.py
Labels: fix

#77 error발생으로 인해 코드 수정
  config/settings/base.py
  users/serializers.py
  users/views.py
Labels: fix

#78 .
  users/views.py
Labels: fix

#79 logger 추가
  users/views.py
Labels: fix

#80 .
  users/views.py
Labels: fix

#81 user_id logger추가
  users/tests.py
  users/views.py
Labels: bug

#82 .
  users/views.py
Labels: bug

#84 .////////.
  users/views.py
Labels: bug

#85 .////////.
  users/views.py
Labels: bug

#87 .
  config/settings/base.py
  config/settings/local.py
Labels: fix

#88 Fix/login
  config/settings/base.py
  config/settings/local.py
  config/settings/prod.py
  users/utils.py
Labels: add tech, fix

#89 프론트 배포 주소에 대한 정보 추가 및 수정
  config/settings/base.py
  config/settings/prod.py
  users/utils.py
  users/views.py
Labels: fix

#90 소셜 로그인 날아간 코드 복구
  users/views.py
Labels: fix

#93 withdraw_at -> user_active가 False로 지정이 안되는 것같아서 logger추가
  users/views.py
Labels: bug

#94 사용자 탈퇴 부분 코드 수정
  users/views.py
Labels: fix

#95 Fix/delete
  .idea/misc.xml
  .idea/toonchu.iml
  users/migrations/0004_customuser_is_active.py
  users/models.py
  users/views.py
Labels: fix

#96 user.is_active -> False -> 0으로 변경
  users/utils.py
  users/views.py
Labels: fix

#97 logoutview rasise주석 처리
  .idea/dataSources.xml
  .idea/misc.xml
  .idea/toonchu.iml
  users/views.py
Labels: add tech

#98 Fix/cors
  config/settings/base.py
  poetry.lock
  pyproject.toml
  webtoons/serializers.py
  webtoons/views.py
Labels: fix

#99 NCP Object Storage설정 및 profile_img 업로드 코드 수정 완료
  config/settings/base.py
  config/utils.py
  poetry.lock
  pyproject.toml
  users/delete_users.py
  users/migrations/0005_customuser_is_hidden.py
  users/models.py
  users/views.py
Labels: add tech, fix

#100 Fix/delete
  config/settings/base.py
  config/utils.py
  poetry.lock
  users/views.py
Labels: fix

#101 access token 시간 10초로 축소
  config/settings/base.py
  users/views.py
Labels: fix

#102 access token 시간 30분으로 원복
  config/settings/base.py
Labels: fix

#104 Object Storage 설정 변경
  config/settings/base.py
  users/views.py
Labels: fix

#106 parser_class 주석 해제
  users/views.py
Labels: fix

#107 access token 시간 다시 설정
  config/settings/base.py
Labels: fix

#108 권한 수정 및 logger 추가
  users/views.py
Labels: fix

#109 Fix/delete
  config/settings/base.py
  users/serializers.py
  users/tests.py
  users/views.py
Labels: fix

#111 Fix/myeong
  config/settings/base.py
  config/settings/local.py
  config/settings/prod.py
  configure_cors.py
  users/profile/test_image.png
  users/tests.py
  users/tests/__init__.py
  users/tests/test_ncp_connection.py
  users/tests/tests_img.py
  users/utils.py
  users/views.py
Labels: fix

#112 ...
  config/settings/base.py
  config/settings/local.py
  config/settings/prod.py
Labels: fix

#113 Webtoon
  webtoons/migrations/0006_alter_tag_tag_name.py
  webtoons/migrations/0007_webtoon_is_approved.py
  webtoons/migrations/0008_alter_webtoon_is_approved.py
  webtoons/models.py
  webtoons/serializers.py
  webtoons/urls.py
  webtoons/utils/image_handler.py
  webtoons/views.py
Labels: add tech, fix

#118 userprofile 오류 코드 수정
  users/views.py
Labels: fix

#119 ncp 환경변수 못 찾는거 -> AWS_STORAGE_BUCKET_NAME 잘못 설정돈부분 수정
  users/views.py
Labels: fix

#126 ...
  users/serializers.py
  users/views.py
Labels: fix

#127 ncp 코드 수정
  ncp/views.py
  users/views.py
Labels: fix

#169 북마크 기능 수정, 이미지 업로드 코드 수정 (프론트와 테스트 필요)
  bookmark/views.py
  users/img_utils.py
  users/views.py
Labels: fix

#170 bokkmark코드 수정 및 연속클릭 방지 로직 추가
  bookmark/views.py
  users/img_utils.py
Labels: fix
